### ISSUE TITLE
BurntSushi/xgb is deprecated, use github.com/jezek/xgb

### ISSUE THREAD

**Issue by tenfourty** [muesli/deckmaster#11]
I noticed that some some of your code can be a bit glitchy... I've not done enough investigation but I see you use the library https://github.com/BurntSushi/xgb which says:

> Note that this project is largely unmaintained as I don't have the time to do
or support more development. Please consider using this fork instead:
https://github.com/jezek/xgb

**Comment by muesli** [comment]
Thanks for the heads up! Can you be a bit more specific tho, please, I haven't noticed any glitches so far.

**Comment by tenfourty** [comment]
I think the main glitches I've seen are not detecting all the windows or more accurately getting the icons for all windows - a good example of an app where it fails is Spotify but there are others.
Since I raised this issue I actually recompiled deckmaster with jezek/xgb but it didn't actually make a difference so I don't think that is the cause.
That said it might still make sense to a more supported version of the libraries?

**Comment by muesli** [comment]
I agree, we should migrate to a maintained version of this. Could you do me two favors:

1. open a ticket for the issue you're seeing, so we can try to reproduce and debug this?
2. if you already made the switch to jezek's package, could you open a PR for that?

Thank you!

**Comment by tenfourty** [comment]
done, PR created. Will create another issue for the window issues.

**Comment by tenfourty** [comment]
created #13 for the XWindows icon issue.
