### ISSUE TITLE
"no Stream Deck devices found" for new (?) StreamDeck Mini

### ISSUE THREAD

**Issue by jamespo** [muesli/deckmaster#114]
I have a new StreamDeck mini with USB ID 0fd9:0090

Bus 001 Device 007: ID 0fd9:0090 Elgato Systems GmbH Stream Deck Mini

I've added this to udev rules and reloaded.

I've tried the various packages on Arch and built myself. Also quickly tried on Fedora and running as root, I always get the "no Stream Deck devices found" error.

Could there be some incompatibility with this version (I presume it's more recent)?

Looks fine in lsusb, dmesg etc. Also works as expected in Windows and in Arch in the python streamdeck-ui.

**Comment by muesli** [comment]
Support for the Mini Mk2 is now in `v0.9.0`: https://github.com/muesli/deckmaster/releases/tag/v0.9.0
