### ISSUE TITLE
Can this be used with Streamdeck-UI?

### ISSUE THREAD

**Issue by oparada1988** [muesli/deckmaster#138]
I want to designate a button for Time, and another for the Weather, can this be used with conjuction with Streamdeck-UI? https://github.com/streamdeck-linux-gui/streamdeck-linux-gui

**Comment by fearlessgeekmedia** [comment]
I could be wrong, but I don't think so. Streamdeck-UI is just another program that does largely the same thing as Deckmaster does. I can't get Deckmaster to work, but I imagine one would complain it couldn't see it if you tried to use them together.

What I can get t work are Streamdeck-UI and Boatswain, but if I try to run the together, only the first one I ran sees my Stream Deck XL. The other one can't see it. I assume the same would be true for running Streamdeck-UI and Deckmaster together.

**Comment by oparada1988** [comment]
I really like the widgets Deckmaster offers :-(
