### ISSUE TITLE
Is Deckmaster wayland ready or fails?

### ISSUE THREAD

**Issue by rastarr** [muesli/deckmaster#139]
I'm running swayvm and wayland
Does deckmaster work under wayland?

If yes, I'll continue trying to get things to work with sway on nixOS

If no, suggestions on a Streamdeck program that works with wayland, with more functionality than the very limited boatswain

Thanks for replies

**Comment by muesli** [comment]
Yeah, generally speaking it works. There are still a few X-protocol dependent implementations, like capturing recently activated / open windows, which we might not be able to fully port over to Wayland however.

**Comment by rastarr** [comment]
hey thanks so much for the explaination. I did notice recently activated windows were working, during my test.
