### ISSUE TITLE
deckmaster doesnt run 

### ISSUE THREAD

**Issue by fallen1011** [muesli/deckmaster#19]
![2021-04-29-232520_1726x141_scrot](https://user-images.githubusercontent.com/29430595/116644751-378f3580-a942-11eb-902d-f73688eb0299.png)

when i rune deckmaster with any provided sample it doesnt load. i get the following errors.

**Comment by muesli** [comment]
Which version of the Deck is that? Until we implement image scaling, I assume you could work around that issue by resizing the images you reference in the `.deck` files to 96x96 pixels.

**Comment by fallen1011** [comment]
the problem is theres nothing in my deckmaster file that i can tell is calling for a img. 

deckmaster-git r70.0a0b293-1

[[keys]]
  index = 0
  [keys.widget]
    id = "button"
    [keys.widget.config]
      icon = ""
  [keys.action]
    paste = ""

[[keys]]
  index = 1
  [keys.widget]
    id = "button"
    [keys.widget.config]
      icon = ""
  [keys.action]
    paste = ""

[[keys]]
  index = 2
  [keys.widget]
    id = "button"
    [keys.widget.config]
      icon = ""
  [keys.action]
    paste = ""

[[keys]]
  index = 3
  [keys.widget]
    id = "button"
    [keys.widget.config]
      icon = ""
  [keys.action]
    paste = ""

[[keys]]
  index = 4
  [keys.widget]
    id = "button"
    [keys.widget.config]
      icon = ""
  [keys.action]
    paste = ""

[[keys]]
  index = 5
  [keys.widget]
    id = "button"
    [keys.widget.config]
      icon = ""
  [keys.action]
    paste = ""

[[keys]]
  index = 6
  [keys.widget]
    id = "button"
    [keys.widget.config]
      icon = ""
  [keys.action]
    paste = ""

[[keys]]
  index = 7
  [keys.widget]
    id = "button"
    [keys.widget.config]
      icon = ""
  [keys.action]
    paste = ""

[[keys]]
  index = 8
  [keys.widget]
    id = "button"
    [keys.widget.config]
      icon = ""
  [keys.action]
    paste = ""

[[keys]]
  index = 9
  [keys.widget]
    id = "button"
    [keys.widget.config]
      icon = ""
  [keys.action]
    paste = ""

[[keys]]
  index = 13
  [keys.widget]
    id = "button"
    [keys.widget.config]
      icon = ""
      label = ""
  [keys.action]
    deck = ""

[[keys]]
  index = 14
  [keys.widget]
    id = "button"
    [keys.widget.config]
      icon = ""
      label = ""
  [keys.action]
    deck = ""

**Comment by muesli** [comment]
Oh, sorry, I meant which version of the Elgato Streamdeck (the hardware) do you have?

**Comment by fallen1011** [comment]
XL, the highest one they sell.

**Comment by muesli** [comment]
Can you try only specifying keys with a valid `icon`? I think it currently requires one. This should be made optional.

**Comment by fallen1011** [comment]
i get the same issue. im using the base assets provided.

**Comment by muesli** [comment]
Can you try it with an image that's 96x96 pixels of size?

**Comment by fallen1011** [comment]
same issue i used this as a test. just googled 96x96 img
![image](https://user-images.githubusercontent.com/29430595/116668821-d67c5780-a96b-11eb-9867-f61582eaf407.png)

**Comment by muesli** [comment]
Ok, thanks for all the help. I think I see what's going on. Should have a fix for this tonight.

**Comment by muesli** [comment]
I can't verify it, but I believe this issue to be fixed in `master` now.
