### ISSUE TITLE
Background-Image (Wallpaper)

### ISSUE THREAD

**Issue by zMoooooritz** [muesli/deckmaster#21]
I got a streamdeck recently and came across your implementation to control the streamdeck.
As I used it, I felt like the "Background-Image"-Feature (from the official software) is missing, this means that most of the time one has to create and apply these background images by hand per widget in an image editor.

Therefore I implemented this feature myself [background](https://github.com/zMoooooritz/deckmaster/commit/3cb4426155e6ee93a2fd7baf98d080f02cadb78e).
Besides the new functionality, it cleans up the different widgets which makes the creation of new ones easier.
One downside of this patch though, is the slightly increased memory footprint as well as some computational overhead for the blending of fore- and background.

As seen in the patch this would also require a small change in [streamdeck](https://github.com/muesli/streamdeck) where we would need a new value for each device which describes the distance / padding between the buttons.

**Comment by muesli** [comment]
Would love to see PRs for these changes!

**Comment by muesli** [comment]
Landed in master!
