### ISSUE TITLE
Any way to define hold actions for buttons?

### ISSUE THREAD

**Issue by HoodedDeath** [muesli/deckmaster#46]
Looking in eventLoop function of main.go, there's a check for if a given key is still pressed for a long press action, and widget_recent_window.go seems to (as far as I can tell) utilize that in order to close a window on long press. So is it currently possible to define a hold action (such as hold a defined key while holding key on the deck) or would it be possible to add such a feature?

**Comment by muesli** [comment]
Yes, you can do that. Instead of (or additional to) using a `[keys.action]` config block, add a `[keys.action_hold]` one. This is apparently missing from the documentation in our README. Will add that and use this ticket to track the status.

**Comment by HoodedDeath** [comment]
Does `[keys.action_hold]` follow the same setup as `[keys.action]`?

**Comment by muesli** [comment]
It does!

**Comment by HoodedDeath** [comment]
Awesome, very good to know. I did already test exactly how the keycode actions worked under `action_hold`, and it works the exact same as the normal `action` by just pressing it momentarily. I honestly expected it to work that way, but I think it would be nice to have the option to hold the key when using `action_hold` and release that key when releasing the button on the deck

**Comment by muesli** [comment]
You mean we should add something like `[keys.action_release]`?

**Comment by muesli** [comment]
`action_hold` is now documented in the README, so I'll close this ticket. Feel free to open a new ticket if you got a specific feature idea. Thank you!
