### ISSUE TITLE
Documentation for interval value listing it under keys section is incorrect

### ISSUE THREAD

**Issue by HoodedDeath** [muesli/deckmaster#47]
The documentation in this repo lists `interval` as being set alongside the `index` value, within the `keys` section. After looking through the code and some testing, I have found out the hard way that the `interval` value needs to be set within the `keys.widget` section, alongside the `id` value. 

Example originally based on documentation:
```
[[keys]]
  index = 0
  interval = 1000
  [keys.widget]
    id = "top"
    [keys.widget.config]
      mode = "cpu"
```

Correct example:
```
[[keys]]
  index = 0
  [keys.widget]
    id = "top"
    interval = 1000
    [keys.widget.config]
      mode = "cpu"
```

**Comment by muesli** [comment]
Fixed by yourself :heart:
