### ISSUE TITLE
Building from source requires Go version >1.13

### ISSUE THREAD

**Issue by helioseven** [muesli/deckmaster#51]
README.md states "Go 1.12 or higher is required", but I just tried to build this on 1.13.4 and got `build github.com/muesli/deckmaster: cannot load embed: malformed module path "embed": missing dot in first path element` error. Upgrading to Go version 1.17.2 resolved this issue.

Proposed solution:
- Just update README.md to reflect higher version number needed.

**Comment by muesli** [comment]
Thank you!
