### ISSUE TITLE
Cannot get deckmaster to discover my stream deck

### ISSUE THREAD

**Issue by lociii** [muesli/deckmaster#54]
deckmaster quits with message `no Stream Deck devices found`

Running Pop!OS 21.04
```
jens@shaun-works:~$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
```

udev rules are set
```
jens@shaun-works:~$ cat /etc/udev/rules.d/99-streamdeck.rules
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0060", MODE:="666", GROUP="plugdev", SYMLINK+="streamdeck"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006d", MODE:="666", GROUP="plugdev", SYMLINK+="streamdeck"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0080", MODE:="666", GROUP="plugdev", SYMLINK+="streamdeck"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0063", MODE:="666", GROUP="plugdev", SYMLINK+="streamdeck-mini"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006c", MODE:="666", GROUP="plugdev", SYMLINK+="streamdeck-xl"
```

user is member of the plugdev group
```
jens@shaun-works:~$ groups
jens sudo plugdev docker
```

streamdeck.path
```
jens@shaun-works:~$ cat ~/.config/systemd/user/streamdeck.path 
[Unit]
Description="Stream Deck Device Path"

[Path]
# the device name will be different if you use streamdeck-mini or streamdeck-xl
PathExists=/dev/streamdeck-xl
Unit=streamdeck.service

[Install]
WantedBy=multi-user.target
```

streamdeck.service
```
jens@shaun-works:~$ cat ~/.config/systemd/user/streamdeck.service 
[Unit]
Description=Deckmaster Service

[Service]
# adjust the path to deckmaster and .deck file to suit your needs
ExecStart=/usr/bin/deckmaster --deck /home/jens/streamdeck/streamdeck-xl.deck
Restart=on-failure

[Install]
WantedBy=default.target
```

deck config file
```
jens@shaun-works:~$ cat ~/streamdeck/streamdeck-xl.deck
[[keys]]
  index = 0
  [keys.widget]
    id = "top"
    [keys.widget.config]
      mode = "cpu"
      fillColor = "#d497de"
```

stream deck is connected
```
jens@shaun-works:~$ ls -al /dev/streamdeck-xl
lrwxrwxrwx 1 root root 15 Jan  4 09:26 /dev/streamdeck-xl -> bus/usb/001/006
```

Any help is highly appreciated. Thanks!

**Comment by muesli** [comment]
> jens@shaun-works:~$ ls -al /dev/streamdeck-xl
> lrwxrwxrwx 1 root root 15 Jan  4 09:26 /dev/streamdeck-xl -> bus/usb/001/006

Can you double check the permissions of the device file it's pointing to (in this case `/dev/bus/usb/001/006`, but that may change after a reboot)?

**Comment by ngirard** [comment]
Heya,
I'm experiencing the exact same problem here. Ubuntu 21.10.
The abovementionned permissions are fine (lrwxrwxrwx).
`strace` doesn't provide anything helpful at first glance.

**Comment by muesli** [comment]
> Heya, I'm experiencing the exact same problem here. Ubuntu 21.10. The abovementioned permissions are fine (lrwxrwxrwx).

These sound like the permissions displayed for a symlink. Can you resolve it and see what the underlying permissions are, please?

**Comment by ngirard** [comment]
@muesli, sure:
```
crw-rw-rw- 1 root plugdev 189, 260 janv. 21 18:19 /dev/bus/usb/003/005
```

**Comment by ngirard** [comment]
FWIW, no attempt at opening any file from `/dev` can be found in `strace`'s output.

**Comment by fubarhouse** [comment]
Just came across this, I'm curious to use it but it's not connecting...
I'm seeing something similar, but it seems my path is different than the above examples.

`Bus 005 Device 006: ID 0fd9:006d Elgato Systems GmbH Stream Deck original V2`

**Comment by muesli** [comment]
Silly but the most basic question: since everyone in here seems to have a revision 2 device, which version of Deckmaster are you running?

**Comment by lociii** [comment]
Mine identifies as
```
Bus 001 Device 006: ID 0fd9:006c Elgato Systems GmbH Stream Deck XL
```

The model version on the back says `20GAT9901`.

File permissions
```
jens@shaun-works:~$ ls -al /dev/bus/usb/001/006
crw-rw-rw-+ 1 root plugdev 189, 5 Feb 11 09:11 /dev/bus/usb/001/006
```

**Comment by muesli** [comment]
Thanks @lociii!

Can you confirm the version of deckmaster (the software) you're using, too?

**Comment by lociii** [comment]
Used to run `0.6.0` and just updated to `0.7.0 (8e7931c)`.
Only difference is the extended error message. Now saying `Unable to initialize Stream Deck: no Stream Deck devices found`

**Comment by muesli** [comment]
@lociii Can you try un- and replugging your device freshly just before trying v0.7.0 once more?

**Comment by lociii** [comment]
Device ID changed after replugging. Result is still the same.

**Comment by lociii** [comment]
@muesli following your discussion in https://github.com/muesli/streamdeck/pull/12 here is the `lsusb -v` dump for the device

```
Bus 001 Device 006: ID 0fd9:006c Elgato Systems GmbH Stream Deck XL
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x0fd9 Elgato Systems GmbH
  idProduct          0x006c Stream Deck XL
  bcdDevice            2.00
  iManufacturer           1 Elgato
  iProduct                2 Stream Deck XL
  iSerial                 3 <redacted>
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0029
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.10
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     194
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               1
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x02  EP 2 OUT
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0400  1x 1024 bytes
        bInterval               1
Device Qualifier (for other device speed):
  bLength                10
  bDescriptorType         6
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  bNumConfigurations      1
can't get debug descriptor: Resource temporarily unavailable
Device Status:     0x0000
  (Bus Powered)
```

**Comment by muesli** [comment]
@lociii I've just pushed a change to https://github.com/muesli/streamdeck in another attempt to fix this issue. Is there any chance you could try building the latest version by cloning this repo and running `go build` in `cmd/streamdeck-cli`?

Then run: `./streamdeck-cli devices`

Thank you!

**Comment by muesli** [comment]
```
Report Descriptors: 
           ** UNAVAILABLE **
```

This is probably an indicator something's wrong outside of deckmaster's control: if the report descriptors aren't available, we would effectively be unable to communicate with the device - whether we find it or not.

Could you try changing your udev rules as described in the README, but looking like this:

```
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006c", TAG+="uaccess"
```

Don't forget to load the changes with `sudo udevadm control --reload-rules` and to re-plug your StreamDeck.

**Comment by lociii** [comment]
@muesli Sure.

```
jens@shaun-works:~/src/private/streamdeck/cmd/streamdeck-cli$ ./streamdeck-cli devices
Found 1 devices:
Serial <redacted> with 32 keys (ID: 0001:0006:00, firmware 1.00.012)
```

**Comment by muesli** [comment]
> @muesli Sure.
> 
> ```
> jens@shaun-works:~/src/private/streamdeck/cmd/streamdeck-cli$ ./streamdeck-cli devices
> Found 1 devices:
> Serial <redacted> with 32 keys (ID: 0001:0006:00, firmware 1.00.012)
> ```

Now that's even more unexpected. It seems to find the device just find, but my recent change seems to have nothing to do with it.

I'm curious: what happens if you compile deckmaster (go build in the repo's root) manually and run it from the terminal?

Did you apply the udev changes from my previous commit, too?

**Comment by muesli** [comment]
> It works when building from source
> 
> ```
> jens@shaun-works:~/src/private/deckmaster$ ./deckmaster --deck ~/streamdeck/streamdeck-xl.deck
> Could not create virtual input device (/dev/uinput): failed to create virtual keyboard device: could not open device file
> Emulating keyboard events will be disabled!
> ^CShutting down...
> jens@shaun-works:~/src/private/deckmaster$ deckmaster --deck ~/streamdeck/streamdeck-xl.deck
> Unable to initialize Stream Deck: no Stream Deck devices found
> ```

Thank you so much, this finally explains the issues everyone is seeing. It's indeed a packaging problem caused by disabling the `cgo` support.

**Comment by lociii** [comment]
Glad I helped. Really looking forward to enjoy deckmaster now!
Keep up the great work.

**Comment by fubarhouse** [comment]
I'm late to the party but the fix works great!
I can finally move to deckmaster, thank you all.
