### ISSUE TITLE
Deckmaster doesn't close the device cleanly when it fails or is terminated

### ISSUE THREAD

**Issue by henryso** [muesli/deckmaster#55]
The device must be power-cycled to recover from when Deckmaster exits.

**Comment by muesli** [comment]
I can't reproduce this. Which Streamdeck (size and revision) are you using?

**Comment by henryso** [comment]
It's a Streamdeck XL, firmware 1.00.010 (according to Deckmaster).  If I press Control-C on the running deckmaster program, the program stops, leaving the display of the Streamdeck as it was before I pressed Control-C (e.g., the clock stops updating).  If I try to relaunch deckmaster, it complains `panic: hidapi: failed to open device`.  I need to unplug and replug the streamdeck to allow deckmaster to find the device again.

**Comment by henryso** [comment]
Note that the same thing happens if Deckmaster encounters an error in a deck file at runtime (like when I'm switching the active deck file via button press).  The deckmaster process quits out and the device is left in an unresponsive state.

**Comment by muesli** [comment]
Thanks for fixing this!
