### ISSUE TITLE
reuse buttons across multiple decks

### ISSUE THREAD

**Issue by tvidal-net** [muesli/deckmaster#81]
Hi, thank you for this amazing implementation of the stream deck.

I am looking for a way to keep some common buttons (like cpu, memory, weather) present in multiple decks.

Is there any way to keep them in a separate deck file and just **include** them to whichever other deck I want to reuse them to avoid copy/paste everything? I could not find it in the docs.

Regards.

**Comment by muesli** [comment]
Thanks again for providing a PR yourself, awesome stuff!
