### ISSUE TITLE
stream deck display stays black

### ISSUE THREAD

**Issue by lnqs** [muesli/deckmaster#85]
Hey, thanks for the really promising looking project.

Trying to run deckmaster with my stream deck mini nothing is displayed on the buttons of the deck with the latest master branch on my Arch Linux machine.
I don't see any errors in the output of deckmaster and button presses are registered perfectly fine:

```
➜ ./deckmaster -verbose -deck ~/.config/deckmaster/main.deck
Found device with serial BL36K1B46596 (6 buttons, firmware 3.00.001)
wait for event: BadDrawable {NiceName: Drawable, Sequence: 2, BadValue: 0, MinorOpcode: 2, MajorOpcode: 144}
Loading deck: /home/lnqs/.config/deckmaster/main.deck
Triggering long action for key 1
Triggering short action for key 2
```

Anyway, the display stays just black.

I set up the udev rules:

```
➜ cat /etc/udev/rules.d/99-streamdeck.rules
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0060", MODE:="666", GROUP="plugdev", SYMLINK+="streamdeck"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006d", MODE:="666", GROUP="plugdev", SYMLINK+="streamdeck"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0080", MODE:="666", GROUP="plugdev", SYMLINK+="streamdeck"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0063", MODE:="666", GROUP="plugdev", SYMLINK+="streamdeck-mini"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006c", MODE:="666", GROUP="plugdev", SYMLINK+="streamdeck-xl"
```

Access rights should also be fine:

```
➜ ls -l /dev/streamdeck-mini 
lrwxrwxrwx 1 root root 15 Feb 12 00:34 /dev/streamdeck-mini -> bus/usb/001/002

➜ ls -l /dev/bus/usb/001/002
crw-rw-rw- 1 root plugdev 189, 1 Feb 12 01:27 /dev/bus/usb/001/002

➜ groups      
vboxusers input wheel lnqs plugdev
```

My deck config (tried several ones but stuck to this as a minimal example in the end):

```
➜ cat ~/.config/deckmaster/main.deck
[[keys]]
  index = 0
  [keys.widget]
    id = "button"
    [keys.widget.config]
      label = "My Button"
```

Any ideas what might be wrong or how to debug it?

**Comment by muesli** [comment]
I assume the example deck in `decks/main.deck` doesn't work either?

**Comment by lnqs** [comment]
Exactly, that was the first thing I tried until I strap things down.

**Comment by lnqs** [comment]
After playing around with the `streamdeck` library a bit and comparing the headers sent for setting images with the ones sent by [this Python implementation]( https://github.com/abcminiuser/python-elgato-streamdeck) I found the issue.

I'll create a PR to that repository soon.
